language: python
python:
  - "2.7"

services:
  - docker

before_script:
  - docker build -t petepython:latest .

script:
  - echo "hello" 
  - docker run petepython sh -c "/usr/bin/python /home/root/app/pythontest.py"  
